### ISSUE TITLE
Passing params to initial http.get?

### ISSUE THREAD

**Issue by Sgoettschkes** [besughi/elixir-k6#4]
I'm trying to use elixir-k6 for an application that lives behind a login. Right now I have manually created the JWT we use to authenticate the user to access the page and I need to pass this as a cookie when doing the initial request. This means that https://github.com/besughi/elixir-k6/blob/main/priv/templates/utilities/phoenix-liveview.js#L8 does not work for me.

I have manually changed the connect function:

```
connect(callback, getParams, parseBody = this._parseBody) {
  let response = http.get(this.url.toString(), getParams);
  // ...
}
```

Is this something I could contribute to the library (either in this form or any other?

**Comment by dallagi** [comment]
Hi @Sgoettschkes !
IMHO this would be a nice addition to the library, and I like the approach you've taken.
I'd add a default value for the params though, and maybe I'd place it as third param to `connect` for backwards compatibility.

WDYT?

Thanks a lot! :heart:

**Comment by Sgoettschkes** [comment]
Thanks (for merging the PR and getting back to me so fast)!

A default value makes sense and while I agree on backward compatibility, I'm wondering if overwriting the parseBody is more common than passing params to the connect? A call to connect with the getParams as the third param would look like this, right?

`liveview.connect(() => {}, liveview._parseBody, {});`

**Comment by dallagi** [comment]
Fair point, I agree with you - especially considering that this library has barely seen any adoption so far, so backwards compatibility should not be that big of a deal.

Feel free to open a PR whenever you feel like it, thank you!
