### ISSUE TITLE
Visualize end-of-test summaries

### ISSUE THREAD

**Issue by avillen** [besughi/elixir-k6#6]
Hi!

First of all, thanks for the library! I saw the talk about this library in the ElixirConf and it looks really awesome! 

This is a question/feature request. I was thinking if it could make sense to add something to be able to generate graphical summaries reports. I know that you can generate the output using for example `mix k6 run test_example.js --out json=summary.json`, but I was thinking if it could make sense to integrate it with visualization tools. 

As a starting point, I saw this entry in the [k6 documentation](https://k6.io/blog/ways-to-visualize-k6-results/#visualize-end-of-test-summaries) and [k6-reporter](https://github.com/benc-uk/k6-reporter) looks to be easy to integrate, just add this import `import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";` and a handleSummary function:

```javascript
export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data),
  };
}
```

WDYT? Did you consider something similar?

**Comment by dallagi** [comment]
Hi @avillen ,

Thanks for letting me know that this library was mentioned at ElixirConf EU, I wasn't aware :smile:
 
I think having custom (eg. html) end-of-test summaries could be useful to some users, but IMHO adding it to the test templates for this library would be a bit too opinionated and possibly out of scope.

Perhaps we could provide some mechanism to allow users define custom templates instead, but I wonder if this would be actually useful in the real world. wdyt?

**Comment by avillen** [comment]
I totally agree with your arguments about it would be opinionated and out of scope. Thank you so much for your response 😄
